class Countries {
  static List<Map<String, dynamic>> countryList = [
    {"alpha2": "af", "name": "Afghanistan"},
    {"alpha2": "ax", "name": "Åland Islands"},
    {"alpha2": "al", "name": "Albania"},
    {"alpha2": "dz", "name": "Algeria"},
    {"alpha2": "as", "name": "American Samoa"},
    {"alpha2": "ad", "name": "Andorra"},
    {"alpha2": "ao", "name": "Angola"},
    {"alpha2": "ai", "name": "Anguilla"},
    {"alpha2": "aq", "name": "Antarctica"},
    {"alpha2": "ag", "name": "Antigua and Barbuda"},
    {"alpha2": "ar", "name": "Argentina"},
    {"alpha2": "am", "name": "Armenia"},
    {"alpha2": "aw", "name": "Aruba"},
    {"alpha2": "au", "name": "Australia"},
    {"alpha2": "at", "name": "Austria"},
    {"alpha2": "az", "name": "Azerbaijan"},
    {"alpha2": "bs", "name": "Bahamas"},
    {"alpha2": "bh", "name": "Bahrain"},
    {"alpha2": "bd", "name": "Bangladesh"},
    {"alpha2": "bb", "name": "Barbados"},
    {"alpha2": "by", "name": "Belarus"},
    {"alpha2": "be", "name": "Belgium"},
    {"alpha2": "bz", "name": "Belize"},
    {"alpha2": "bj", "name": "Benin"},
    {"alpha2": "bm", "name": "Bermuda"},
    {"alpha2": "bt", "name": "Bhutan"},
    {"alpha2": "bo", "name": "Bolivia (Plurinational State of)"},
    {"alpha2": "bq", "name": "Bonaire, Sint Eustatius and Saba"},
    {"alpha2": "ba", "name": "Bosnia and Herzegovina"},
    {"alpha2": "bw", "name": "Botswana"},
    {"alpha2": "bv", "name": "Bouvet Island"},
    {"alpha2": "br", "name": "Brazil"},
    {"alpha2": "io", "name": "British Indian Ocean Territory"},
    {"alpha2": "bn", "name": "Brunei Darussalam"},
    {"alpha2": "bg", "name": "Bulgaria"},
    {"alpha2": "bf", "name": "Burkina Faso"},
    {"alpha2": "bi", "name": "Burundi"},
    {"alpha2": "cv", "name": "Cabo Verde"},
    {"alpha2": "kh", "name": "Cambodia"},
    {"alpha2": "cm", "name": "Cameroon"},
    {"alpha2": "ca", "name": "Canada"},
    {"alpha2": "ky", "name": "Cayman Islands"},
    {"alpha2": "cf", "name": "Central African Republic"},
    {"alpha2": "td", "name": "Chad"},
    {"alpha2": "cl", "name": "Chile"},
    {"alpha2": "cn", "name": "China"},
    {"alpha2": "cx", "name": "Christmas Island"},
    {"alpha2": "cc", "name": "Cocos (Keeling) Islands"},
    {"alpha2": "co", "name": "Colombia"},
    {"alpha2": "km", "name": "Comoros"},
    {"alpha2": "cg", "name": "Congo"},
    {"alpha2": "cd", "name": "Congo, Democratic Republic of the"},
    {"alpha2": "ck", "name": "Cook Islands"},
    {"alpha2": "cr", "name": "Costa Rica"},
    {"alpha2": "ci", "name": "Côte d'Ivoire"},
    {"alpha2": "hr", "name": "Croatia"},
    {"alpha2": "cu", "name": "Cuba"},
    {"alpha2": "cw", "name": "Curaçao"},
    {"alpha2": "cy", "name": "Cyprus"},
    {"alpha2": "cz", "name": "Czechia"},
    {"alpha2": "dk", "name": "Denmark"},
    {"alpha2": "dj", "name": "Djibouti"},
    {"alpha2": "dm", "name": "Dominica"},
    {"alpha2": "do", "name": "Dominican Republic"},
    {"alpha2": "ec", "name": "Ecuador"},
    {"alpha2": "eg", "name": "Egypt"},
    {"alpha2": "sv", "name": "El Salvador"},
    {"alpha2": "gq", "name": "Equatorial Guinea"},
    {"alpha2": "er", "name": "Eritrea"},
    {"alpha2": "ee", "name": "Estonia"},
    {"alpha2": "sz", "name": "Eswatini"},
    {"alpha2": "et", "name": "Ethiopia"},
    {"alpha2": "fk", "name": "Falkland Islands (Malvinas)"},
    {"alpha2": "fo", "name": "Faroe Islands"},
    {"alpha2": "fj", "name": "Fiji"},
    {"alpha2": "fi", "name": "Finland"},
    {"alpha2": "fr", "name": "France"},
    {"alpha2": "gf", "name": "French Guiana"},
    {"alpha2": "pf", "name": "French Polynesia"},
    {"alpha2": "tf", "name": "French Southern Territories"},
    {"alpha2": "ga", "name": "Gabon"},
    {"alpha2": "gm", "name": "Gambia"},
    {"alpha2": "ge", "name": "Georgia"},
    {"alpha2": "de", "name": "Germany"},
    {"alpha2": "gh", "name": "Ghana"},
    {"alpha2": "gi", "name": "Gibraltar"},
    {"alpha2": "gr", "name": "Greece"},
    {"alpha2": "gl", "name": "Greenland"},
    {"alpha2": "gd", "name": "Grenada"},
    {"alpha2": "gp", "name": "Guadeloupe"},
    {"alpha2": "gu", "name": "Guam"},
    {"alpha2": "gt", "name": "Guatemala"},
    {"alpha2": "gg", "name": "Guernsey"},
    {"alpha2": "gn", "name": "Guinea"},
    {"alpha2": "gw", "name": "Guinea-Bissau"},
    {"alpha2": "gy", "name": "Guyana"},
    {"alpha2": "ht", "name": "Haiti"},
    {"alpha2": "hm", "name": "Heard Island and McDonald Islands"},
    {"alpha2": "va", "name": "Holy See"},
    {"alpha2": "hn", "name": "Honduras"},
    {"alpha2": "hk", "name": "Hong Kong"},
    {"alpha2": "hu", "name": "Hungary"},
    {"alpha2": "is", "name": "Iceland"},
    {"alpha2": "in", "name": "India"},
    {"name": "Indonesia"},
    {"alpha2": "ir", "name": "Iran (Islamic Republic of)"},
    {"alpha2": "iq", "name": "Iraq"},
    {"alpha2": "ie", "name": "Ireland"},
    {"alpha2": "im", "name": "Isle of Man"},
    {"alpha2": "il", "name": "Israel"},
    {"alpha2": "it", "name": "Italy"},
    {"alpha2": "jm", "name": "Jamaica"},
    {"alpha2": "jp", "name": "Japan"},
    {"alpha2": "je", "name": "Jersey"},
    {"alpha2": "jo", "name": "Jordan"},
    {"alpha2": "kz", "name": "Kazakhstan"},
    {"alpha2": "ke", "name": "Kenya"},
    {"alpha2": "ki", "name": "Kiribati"},
    {"alpha2": "kp", "name": "Korea (Democratic People's Republic of)"},
    {"alpha2": "kr", "name": "Korea, Republic of"},
    {"alpha2": "kw", "name": "Kuwait"},
    {"alpha2": "kg", "name": "Kyrgyzstan"},
    {"alpha2": "la", "name": "Lao People's Democratic Republic"},
    {"alpha2": "lv", "name": "Latvia"},
    {"alpha2": "lb", "name": "Lebanon"},
    {"alpha2": "ls", "name": "Lesotho"},
    {"alpha2": "lr", "name": "Liberia"},
    {"alpha2": "ly", "name": "Libya"},
    {"alpha2": "li", "name": "Liechtenstein"},
    {"alpha2": "lt", "name": "Lithuania"},
    {"alpha2": "lu", "name": "Luxembourg"},
    {"alpha2": "mo", "name": "Macao"},
    {"alpha2": "mg", "name": "Madagascar"},
    {"alpha2": "mw", "name": "Malawi"},
    {"alpha2": "my", "name": "Malaysia"},
    {"alpha2": "mv", "name": "Maldives"},
    {"alpha2": "ml", "name": "Mali"},
    {"alpha2": "mt", "name": "Malta"},
    {"alpha2": "mh", "name": "Marshall Islands"},
    {"alpha2": "mq", "name": "Martinique"},
    {"alpha2": "mr", "name": "Mauritania"},
    {"alpha2": "mu", "name": "Mauritius"},
    {"alpha2": "yt", "name": "Mayotte"},
    {"alpha2": "mx", "name": "Mexico"},
    {"alpha2": "fm", "name": "Micronesia (Federated States of)"},
    {"alpha2": "md", "name": "Moldova, Republic of"},
    {"alpha2": "mc", "name": "Monaco"},
    {"alpha2": "mn", "name": "Mongolia"},
    {"alpha2": "me", "name": "Montenegro"},
    {"alpha2": "ms", "name": "Montserrat"},
    {"alpha2": "ma", "name": "Morocco"},
    {"alpha2": "mz", "name": "Mozambique"},
    {"alpha2": "mm", "name": "Myanmar"},
    {"alpha2": "na", "name": "Namibia"},
    {"alpha2": "nr", "name": "Nauru"},
    {"alpha2": "np", "name": "Nepal"},
    {"alpha2": "nl", "name": "Netherlands"},
    {"alpha2": "nc", "name": "New Caledonia"},
    {"alpha2": "nz", "name": "New Zealand"},
    {"alpha2": "ni", "name": "Nicaragua"},
    {"alpha2": "ne", "name": "Niger"},
    {"alpha2": "ng", "name": "Nigeria"},
    {"alpha2": "nu", "name": "Niue"},
    {"alpha2": "nf", "name": "Norfolk Island"},
    {"alpha2": "mk", "name": "North Macedonia"},
    {"alpha2": "mp", "name": "Northern Mariana Islands"},
    {"alpha2": "no", "name": "Norway"},
    {"alpha2": "om", "name": "Oman"},
    {"alpha2": "pk", "name": "Pakistan"},
    {"alpha2": "pw", "name": "Palau"},
    {"alpha2": "ps", "name": "Palestine, State of"},
    {"alpha2": "pa", "name": "Panama"},
    {"alpha2": "pg", "name": "Papua New Guinea"},
    {"alpha2": "py", "name": "Paraguay"},
    {"alpha2": "pe", "name": "Peru"},
    {"alpha2": "ph", "name": "Philippines"},
    {"alpha2": "pn", "name": "Pitcairn"},
    {"alpha2": "pl", "name": "Poland"},
    {"alpha2": "pt", "name": "Portugal"},
    {"alpha2": "pr", "name": "Puerto Rico"},
    {"alpha2": "qa", "name": "Qatar"},
    {"alpha2": "re", "name": "Réunion"},
    {"alpha2": "ro", "name": "Romania"},
    {"alpha2": "ru", "name": "Russian Federation"},
    {"alpha2": "rw", "name": "Rwanda"},
    {"alpha2": "bl", "name": "Saint Barthélemy"},
    {"alpha2": "sh", "name": "Saint Helena, Ascension and Tristan da Cunha"},
    {"alpha2": "kn", "name": "Saint Kitts and Nevis"},
    {"alpha2": "lc", "name": "Saint Lucia"},
    {"alpha2": "mf", "name": "Saint Martin (French part)"},
    {"alpha2": "pm", "name": "Saint Pierre and Miquelon"},
    {"alpha2": "vc", "name": "Saint Vincent and the Grenadines"},
    {"alpha2": "ws", "name": "Samoa"},
    {"alpha2": "sm", "name": "San Marino"},
    {"alpha2": "st", "name": "Sao Tome and Principe"},
    {"alpha2": "sa", "name": "Saudi Arabia"},
    {"alpha2": "sn", "name": "Senegal"},
    {"alpha2": "rs", "name": "Serbia"},
    {"alpha2": "sc", "name": "Seychelles"},
    {"alpha2": "sl", "name": "Sierra Leone"},
    {"alpha2": "sg", "name": "Singapore"},
    {"alpha2": "sx", "name": "Sint Maarten (Dutch part)"},
    {"alpha2": "sk", "name": "Slovakia"},
    {"alpha2": "si", "name": "Slovenia"},
    {"alpha2": "sb", "name": "Solomon Islands"},
    {"alpha2": "so", "name": "Somalia"},
    {"alpha2": "za", "name": "South Africa"},
    {"alpha2": "gs", "name": "South Georgia and the South Sandwich Islands"},
    {"alpha2": "ss", "name": "South Sudan"},
    {"alpha2": "es", "name": "Spain"},
    {"alpha2": "lk", "name": "Sri Lanka"},
    {"alpha2": "sd", "name": "Sudan"},
    {"alpha2": "sr", "name": "Suriname"},
    {"alpha2": "sj", "name": "Svalbard and Jan Mayen"},
    {"alpha2": "se", "name": "Sweden"},
    {"alpha2": "ch", "name": "Switzerland"},
    {"alpha2": "sy", "name": "Syrian Arab Republic"},
    {"alpha2": "tw", "name": "Taiwan, Province of China"},
    {"alpha2": "tj", "name": "Tajikistan"},
    {"alpha2": "tz", "name": "Tanzania, United Republic of"},
    {"alpha2": "th", "name": "Thailand"},
    {"alpha2": "tl", "name": "Timor-Leste"},
    {"alpha2": "tg", "name": "Togo"},
    {"alpha2": "tk", "name": "Tokelau"},
    {"alpha2": "to", "name": "Tonga"},
    {"alpha2": "tt", "name": "Trinidad and Tobago"},
    {"alpha2": "tn", "name": "Tunisia"},
    {"alpha2": "tr", "name": "Turkey"},
    {"alpha2": "tm", "name": "Turkmenistan"},
    {"alpha2": "tc", "name": "Turks and Caicos Islands"},
    {"alpha2": "tv", "name": "Tuvalu"},
    {"alpha2": "ug", "name": "Uganda"},
    {"alpha2": "ua", "name": "Ukraine"},
    {"alpha2": "ae", "name": "United Arab Emirates"},
    {
      "alpha2": "gb",
      "name": "United Kingdom of Great Britain and Northern Ireland"
    },
    {"alpha2": "us", "name": "United States of America"},
    {"alpha2": "um", "name": "United States Minor Outlying Islands"},
    {"alpha2": "uy", "name": "Uruguay"},
    {"alpha2": "uz", "name": "Uzbekistan"},
    {"alpha2": "vu", "name": "Vanuatu"},
    {"alpha2": "ve", "name": "Venezuela (Bolivarian Republic of)"},
    {"alpha2": "vn", "name": "Viet Nam"},
    {"alpha2": "vg", "name": "Virgin Islands (British)"},
    {"alpha2": "vi", "name": "Virgin Islands (U.S.)"},
    {"alpha2": "wf", "name": "Wallis and Futuna"},
    {"alpha2": "eh", "name": "Western Sahara"},
    {"alpha2": "ye", "name": "Yemen"},
    {"alpha2": "zm", "name": "Zambia"},
    {"alpha2": "zw", "name": "Zimbabwe"}
  ];
}
